## Oil & Inflation Data

### Setup

In [12]:
# libraries
import matplotlib.pyplot as plt ## for basic plotting
import matplotlib as mpl ## for setting default parameters
import pandas as pd ## always
import os ## for handling file paths 1
from pathlib import Path ## for handling file paths 2
import numpy as np ## for numerical operations
import seaborn as sns ## for more advanced plotting

In [13]:
# paths
base_dir = Path("/Users/hannahmaihojgaard/Documents/GitHub/datascience2026")
data_path = Path(base_dir / "data")

### Load in data

In [14]:
oil_df = pd.read_csv(data_path / "DCOILBRENTEU.csv")

In [15]:
oil_df.head()

  observation_date  DCOILBRENTEU
0       2021-01-04         50.37
1       2021-01-05         53.16
2       2021-01-06         53.80
3       2021-01-07         53.70
4       2021-01-08         55.51

In [16]:
oil_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1389 entries, 0 to 1388
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  1389 non-null   object
 1   DCOILBRENTEU      1346 non-null   float64
dtypes: float64(1), object(1)
memory usage: 21.8+ KB

### Clean data

In [17]:
# rename columns
oil_df = oil_df.rename(columns={
    "observation_date": "date",
    "DCOILBRENTEU": "oil_price"
})

# convert date column to datetime
oil_df["date"] = pd.to_datetime(oil_df["date"])

oil_df.head()

        date  oil_price
0 2021-01-04      50.37
1 2021-01-05      53.16
2 2021-01-06      53.80
3 2021-01-07      53.70
4 2021-01-08      55.51

In [18]:
# check for missing values
oil_df["oil_price"] = oil_df["oil_price"].ffill()

In [19]:
oil_df.isna().sum()

date         0
oil_price    0
dtype: int64

In [20]:
# create complete daily date range
full_dates = pd.DataFrame({
    "date": pd.date_range(
        start=oil_df["date"].min(),
        end=oil_df["date"].max(),
        freq="D"
    )
})

# merge oil data onto complete date range
oil_df_daily = full_dates.merge(
    oil_df,
    on="date",
    how="left"
)

# forward-fill missing oil prices
oil_df_daily["oil_price"] = oil_df_daily["oil_price"].ffill()

# check missing values
oil_df_daily.isna().sum()

date         0
oil_price    0
dtype: int64

In [21]:
oil_df.head()

        date  oil_price
0 2021-01-04      50.37
1 2021-01-05      53.16
2 2021-01-06      53.80
3 2021-01-07      53.70
4 2021-01-08      55.51

In [11]:
oil_df.to_parquet(
    data_path / "oil_cleaned_daily.parquet",
    index=False
)